baseURL = 'https://aquarium-project.pages.dev/'
languageCode = 'en-us'
title = 'Aquarium Products Store'

[taxonomies]
  type = 'type'
  subType = 'subType'
  category = 'category'
  subCategory = 'subCategory'
  brand = 'brand'
