baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'aquarium'

[main]
  [[menu.main]]
    identifier = "products"
    name       = "view all products"
    url        = "/products/"
    weight     = 1
    